
<button type="button" class="action-size-chart" data-trigger="trigger">
    <span data-bind="i18n: 'Size Chart'"></span>
</button>
<div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'title': 'SIZE CHART',
            'trigger': '[data-trigger=trigger]',
            'responsive': true,
            'buttons': [{
                text: jQuery.mage.__('OK'),
                class: 'action'
            }]
        }}">
    <div class="content">
        <div class="box_content">
            <h3>FEMALE CLOTHING CONVERSION CHART &amp;&nbsp;MEASUREMENT REFERENCES</h3>
            <table class="size-chart" style="width: 100%; height: 252px;">
                <tbody>
                <tr class="odd">
                    <td>UK</td>
                    <td style="text-align: center;">6</td>
                    <td style="text-align: center;">8</td>
                    <td style="text-align: center;">10</td>
                    <td style="text-align: center;">12</td>
                    <td style="text-align: center;">14</td>
                    <td style="text-align: center;">16</td>
                    <td style="text-align: center;">18</td>
                    <td style="text-align: center;">20</td>
                    <td style="text-align: center;">22</td>
                    <td style="text-align: center;">24</td>
                    <td style="text-align: center;">26</td>
                    <td style="text-align: center;">28</td>
                </tr>
                <tr>
                    <td>FRANCE (DEFAULT)</td>
                    <td style="text-align: center;">34</td>
                    <td style="text-align: center;">36</td>
                    <td style="text-align: center;">38</td>
                    <td style="text-align: center;">40</td>
                    <td style="text-align: center;">42</td>
                    <td style="text-align: center;">44</td>
                    <td style="text-align: center;">46</td>
                    <td style="text-align: center;">48</td>
                    <td style="text-align: center;">50</td>
                    <td style="text-align: center;">52</td>
                    <td style="text-align: center;">54</td>
                    <td style="text-align: center;">56</td>
                </tr>
                <tr class="odd">
                    <td>ITALY</td>
                    <td style="text-align: center;">38</td>
                    <td style="text-align: center;">40</td>
                    <td style="text-align: center;">42</td>
                    <td style="text-align: center;">44</td>
                    <td style="text-align: center;">46</td>
                    <td style="text-align: center;">48</td>
                    <td style="text-align: center;">50</td>
                    <td style="text-align: center;">52</td>
                    <td style="text-align: center;">54</td>
                    <td style="text-align: center;">56</td>
                    <td style="text-align: center;">58</td>
                    <td style="text-align: center;">60</td>
                </tr>
                <tr>
                    <td>USA</td>
                    <td style="text-align: center;">2</td>
                    <td style="text-align: center;">4</td>
                    <td style="text-align: center;">6</td>
                    <td style="text-align: center;">8</td>
                    <td style="text-align: center;">10</td>
                    <td style="text-align: center;">12</td>
                    <td style="text-align: center;">14</td>
                    <td style="text-align: center;">16</td>
                    <td style="text-align: center;">18</td>
                    <td style="text-align: center;">20</td>
                    <td style="text-align: center;">22</td>
                    <td style="text-align: center;">24</td>
                </tr>
                <tr class="odd">
                    <td>JAPAN</td>
                    <td style="text-align: center;">5</td>
                    <td style="text-align: center;">7</td>
                    <td style="text-align: center;">9</td>
                    <td style="text-align: center;">11</td>
                    <td style="text-align: center;">13</td>
                    <td style="text-align: center;">15</td>
                    <td style="text-align: center;">17</td>
                    <td style="text-align: center;">19</td>
                    <td style="text-align: center;">21</td>
                    <td style="text-align: center;">23</td>
                    <td style="text-align: center;">25</td>
                    <td style="text-align: center;">27</td>
                </tr>
                <tr>
                    <td>AUSTRALIA</td>
                    <td style="text-align: center;">6</td>
                    <td style="text-align: center;">8</td>
                    <td style="text-align: center;">10</td>
                    <td style="text-align: center;">12</td>
                    <td style="text-align: center;">14</td>
                    <td style="text-align: center;">16</td>
                    <td style="text-align: center;">18</td>
                    <td style="text-align: center;">20</td>
                    <td style="text-align: center;">22</td>
                    <td style="text-align: center;">24</td>
                    <td style="text-align: center;">26</td>
                    <td style="text-align: center;">28</td>
                </tr>
                <tr class="odd">
                    <td>INTERNATIONAL</td>
                    <td style="text-align: center;">XS</td>
                    <td style="text-align: center;">S</td>
                    <td style="text-align: center;">M</td>
                    <td style="text-align: center;">L</td>
                    <td style="text-align: center;">XL</td>
                    <td style="text-align: center;">2XL</td>
                    <td style="text-align: center;">3XL</td>
                    <td style="text-align: center;">4XL</td>
                    <td style="text-align: center;">5XL</td>
                    <td style="text-align: center;">6XL</td>
                    <td style="text-align: center;">7XL</td>
                    <td style="text-align: center;">8XL</td>
                </tr>
                <tr>
                    <td>BUST (cm)</td>
                    <td style="text-align: center;">81-83</td>
                    <td style="text-align: center;">83-89</td>
                    <td style="text-align: center;">89-96</td>
                    <td style="text-align: center;">96-103</td>
                    <td style="text-align: center;">103-107</td>
                    <td style="text-align: center;">107-111</td>
                    <td style="text-align: center;">111-115</td>
                    <td style="text-align: center;">115-120</td>
                    <td style="text-align: center;">120-125</td>
                    <td style="text-align: center;">125-130</td>
                    <td style="text-align: center;">130-135</td>
                    <td style="text-align: center;">135-140</td>
                </tr>
                <tr class="odd">
                    <td>WAIST (cm)</td>
                    <td style="text-align: center;">61-64</td>
                    <td style="text-align: center;">64-68</td>
                    <td style="text-align: center;">68-75</td>
                    <td style="text-align: center;">75-81</td>
                    <td style="text-align: center;">81-86</td>
                    <td style="text-align: center;">86-91</td>
                    <td style="text-align: center;">91-97</td>
                    <td style="text-align: center;">97-102</td>
                    <td style="text-align: center;">102-107</td>
                    <td style="text-align: center;">107-112</td>
                    <td style="text-align: center;">112-117</td>
                    <td style="text-align: center;">117-122</td>
                </tr>
                <tr>
                    <td>HIPS (cm)</td>
                    <td style="text-align: center;">86-90</td>
                    <td style="text-align: center;">90-94</td>
                    <td style="text-align: center;">94-98</td>
                    <td style="text-align: center;">98-102</td>
                    <td style="text-align: center;">102-106</td>
                    <td style="text-align: center;">106-110</td>
                    <td style="text-align: center;">110-114</td>
                    <td style="text-align: center;">114-119</td>
                    <td style="text-align: center;">119-124</td>
                    <td style="text-align: center;">124-129</td>
                    <td style="text-align: center;">129-134</td>
                    <td style="text-align: center;">134-139</td>
                </tr>
                </tbody>
            </table>
            <h3></h3>
            <p></p></div>
    </div>
</div>

